=== skornel02/skornel02/schema/achievements.schema.json
{"$ref":"#/definitions/achievementSchema","definitions":{"achievementSchema":{"type":"object","properties":{"name":{"type":"string"},"date":{"type":"string","format":"date-time"},"placement":{"type":"string"},"icon":{"type":"string"},"iconColor":{"type":"string","default":"orange"},"highlighted":{"type":"boolean","default":false},"images":{"type":"array","items":{"type":"object","properties":{"src":{"type":"string"},"alt":{"type":"string"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:file-image-box"},"buttonClass":{"type":"string","default":"btn btn-sm btn-primary text-white"}},"required":["src","alt","name"],"additionalProperties":false},"default":[]},"pdfs":{"type":"array","items":{"type":"object","properties":{"src":{"type":"string"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:file-pdf"},"buttonClass":{"type":"string","default":"btn btn-sm btn-primary text-white"}},"required":["src","name"],"additionalProperties":false},"default":[]},"urls":{"type":"array","items":{"type":"object","properties":{"href":{"type":"string","format":"uri"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:link-variant"},"buttonClass":{"type":"string","default":"btn btn-sm btn-secondary text-white"}},"required":["href","name"],"additionalProperties":false},"default":[]},"team":{"type":"array","items":{"anyOf":[{"type":"string"},{"type":"object","properties":{"id":{"type":"string"},"collection":{"type":"string"}},"required":["id","collection"],"additionalProperties":false},{"type":"object","properties":{"slug":{"type":"string"},"collection":{"type":"string"}},"required":["slug","collection"],"additionalProperties":false}]}},"blogPost":{"anyOf":[{"type":"string"},{"type":"object","properties":{"id":{"type":"string"},"collection":{"type":"string"}},"required":["id","collection"],"additionalProperties":false},{"type":"object","properties":{"slug":{"type":"string"},"collection":{"type":"string"}},"required":["slug","collection"],"additionalProperties":false}]},"coverImage":{"type":"object","properties":{"src":{"type":"string"},"alt":{"type":"string"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:file-image-box"},"buttonClass":{"type":"string","default":"btn btn-sm btn-primary text-white"}},"required":["src","alt","name"],"additionalProperties":false}},"required":["name","date","placement","icon"],"additionalProperties":false,"description":"Achievements schema"}},"$schema":"http://json-schema.org/draft-07/schema#"}

=== skornel02/skornel02/website/src/content/achievements/2019-webex.json
{
	"$schema": "https://skornel02.hu/schema/competition.schema.json",
	"name": "Http Alapítvány - Cisco Webex Hacathlon - 2019",
	"date": "2019-04-12",
	"placement": "I. place",
	"icon": "mdi:trophy-award",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Webex-Teams-Hackathlon-2019-photo.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"team": ["erik", "partfo", "sk"]
}

=== skornel02/skornel02/website/src/content/competitions/2021-merklik.json
{
	"$schema": "../../schemas/competition.schema.json",
	"name": "II. Merklik László problémamegoldó verseny",
	"date": "2021-04-15",
	"placement": "Finalist",
	"icon": "emojione-monotone:1st-place-medal",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Merklik-2021.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
    "team": ["partfo", "sk", "avar"]
}

=== skornel02/skornel02/website/src/content/achievements/2021-bbb.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "Bakonyi Bitfaragó Bajnokság - 2021",
	"date": "2021-11-20",
	"placement": "I. place",
	"icon": "mdi:trophy-award",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Bakonyi-Bitfarago-Bajnoksag-2021.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"urls": [
		{
			"name": "Repository",
			"href": "https://github.com/skornel02/b3-2021",
			"icon": "mdi:source-repository"
		},
		{
			"name": "Website",
			"href": "https://mik.uni-pannon.hu/szervezet/hirek/kar-tovabbi-hirei/bakonyi-bitfarago-bajnoksag-2022"
		}
	],
	"team": ["partfo", "sk", "avar"]
}

=== skornel02/skornel02/website/src/content/competitions/2021-innovacio.json
{
	"$schema": "https://skornel02.hu/schema/competition.schema.json",
	"name": "30. Ifjúsági Tudományos és Innovációs Tehetségkutató Verseny",
	"date": "2021-06-22",
	"placement": "Finalist",
	"icon": "mdi:star",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Innovacios-tehetsegkutato-2021.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"team": ["sk", "avar"]
}

=== skornel02/skornel02/website/src/content/achievements/2023-ws-preliminary.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "WorldSkills 2024 qualifier - IT Software Solutions for Business",
	"date": "2023-04-26",
	"placement": "I. place",
	"icon": "mdi:trophy-award",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/WorldSkills-Qualifier-2023.jpg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"urls": [
		{
			"name": "Official website",
			"href": "https://www.worldskillshungary.hu/versenyek/worldskills-lyon-2024"
		}
	]
}

=== skornel02/skornel02/website/src/content/achievements/2020-bbb.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "Bakonyi Bitfaragó Bajnokság - 2020",
	"date": "2021-04-17",
	"placement": "I. place",
	"icon": "mdi:trophy-award",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Bakonyi-Bitfarago-Bajnoksag-2020.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"urls": [
		{
			"name": "Competition website",
			"href": "https://mik.uni-pannon.hu/szervezet/hirek/kar-tovabbi-hirei/osszefoglalo-a-8-bakonyi-bitfarago-bajnoksagrol"
		}
	],
	"team": ["partfo", "sk", "avar"]
}

=== skornel02/skornel02/website/src/content/competitions/2021-bbb.json
{
	"$schema": "../../../dist/schema/competition.schema.json",
	"name": "Bakonyi Bitfaragó Bajnokság - 2021",
	"date": "2021-11-20",
	"placement": "First place",
	"icon": "emojione-monotone:1st-place-medal",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Bakonyi-Bitfarago-Bajnoksag-2021.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"urls": [
		{
			"name": "Repository",
			"href": "https://github.com/skornel02/b3-2021",
			"icon": "mdi:source-repository"
		},
		{
			"name": "Website",
			"href": "https://mik.uni-pannon.hu/szervezet/hirek/kar-tovabbi-hirei/bakonyi-bitfarago-bajnoksag-2022"
		}
	],
	"team": ["partfo", "sk", "avar"]
}

=== skornel02/skornel02/website/src/content/achievements/2021-neu.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "Neumann János Egyetem Programming contest - 2020",
	"date": "2021-01-27",
	"placement": "II. place",
	"icon": "mdi:medal-outline",
	"highlighted": false,
	"pdfs": [
		{
			"name": "Competition certificate",
			"src": "/competitions/GAMF programozó verseny 2020.pdf"
		}
	],
	"team": ["partfo", "erik", "sk"]
}
