=== skornel02/skornel02/schema/achievements.schema.json
{"$ref":"#/definitions/achievementSchema","definitions":{"achievementSchema":{"type":"object","properties":{"name":{"type":"string"},"date":{"type":"string","format":"date-time"},"placement":{"type":"string"},"icon":{"type":"string"},"iconColor":{"type":"string","default":"orange"},"highlighted":{"type":"boolean","default":false},"images":{"type":"array","items":{"type":"object","properties":{"src":{"type":"string"},"alt":{"type":"string"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:file-image-box"},"buttonClass":{"type":"string","default":"btn btn-sm btn-primary text-white"}},"required":["src","alt","name"],"additionalProperties":false},"default":[]},"pdfs":{"type":"array","items":{"type":"object","properties":{"src":{"type":"string"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:file-pdf"},"buttonClass":{"type":"string","default":"btn btn-sm btn-primary text-white"}},"required":["src","name"],"additionalProperties":false},"default":[]},"urls":{"type":"array","items":{"type":"object","properties":{"href":{"type":"string","format":"uri"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:link-variant"},"buttonClass":{"type":"string","default":"btn btn-sm btn-secondary text-white"}},"required":["href","name"],"additionalProperties":false},"default":[]},"team":{"type":"array","items":{"anyOf":[{"type":"string"},{"type":"object","properties":{"id":{"type":"string"},"collection":{"type":"string"}},"required":["id","collection"],"additionalProperties":false},{"type":"object","properties":{"slug":{"type":"string"},"collection":{"type":"string"}},"required":["slug","collection"],"additionalProperties":false}]}},"blogPost":{"anyOf":[{"type":"string"},{"type":"object","properties":{"id":{"type":"string"},"collection":{"type":"string"}},"required":["id","collection"],"additionalProperties":false},{"type":"object","properties":{"slug":{"type":"string"},"collection":{"type":"string"}},"required":["slug","collection"],"additionalProperties":false}]},"coverImage":{"type":"object","properties":{"src":{"type":"string"},"alt":{"type":"string"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:file-image-box"},"buttonClass":{"type":"string","default":"btn btn-sm btn-primary text-white"}},"required":["src","alt","name"],"additionalProperties":false}},"required":["name","date","placement","icon"],"additionalProperties":false,"description":"Achievements schema"}},"$schema":"http://json-schema.org/draft-07/schema#"}

=== skornel02/skornel02/website/src/content/achievements/2019-nemes.json
{
	"$schema": "https://skornel02.hu/schema/competition.schema.json",
	"name": "Nemes Tihamér Nemzetközi Informatikai Tanulmányi Verseny - 2019 - Programming category",
	"date": "2019-04-05",
	"placement": "41. place",
	"icon": "mdi:star",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Nemes-Tihamer-2019.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	]
}

=== skornel02/skornel02/website/src/content/competitions/2021-khn.json
{
	"$schema": "https://skornel02.hu/schema/competition.schema.json",
	"name": "Kódolj Határok Nélkül! - 2021",
	"date": "2021-06-01",
	"placement": "Finalist",
	"icon": "emojione-monotone:1st-place-medal",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Kodolj-Hatarok-Nelkul-2021.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"urls": [
		{
			"name": "Repository",
			"href": "https://github.com/skornel02/khn2021"
		}
	],
	"team": ["ruzsa", "sk", "avar"]
}

=== skornel02/skornel02/website/src/content/competitions/2020-dusza-mobil.json
{
	"$schema": "https://skornel02.hu/schema/competition.schema.json",
	"name": "Dusza Árpád Országos Programozói Emlékverseny - 2020 - Mobile category",
	"date": "2020-12-05",
	"placement": "I. place",
	"icon": "mdi:trophy-award",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Dusza-mobil-2020.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"urls": [{"name": "Repository", "href": "https://github.com/skornel02/duszamobile2020"}],
	"pdfs": [],
	"team": ["erik", "partfo", "sk"]
}

=== skornel02/skornel02/website/src/content/achievements/2020-dusza-trad.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "Dusza Árpád Országos Programozói Emlékverseny - 2020 - Traditional category",
	"date": "2020-02-22",
	"placement": "II. place",
	"icon": "mdi:medal-outline",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Dusza-2020.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"team": ["erik", "partfo", "sk"]
}

=== skornel02/skornel02/website/src/content/competitions/2022-ifju-tudosok.json
{
	"$schema": "https://skornel02.hu/schema/competition.schema.json",
	"name": "Ifjútudosok tudományos vetélkedő - 2022 - Traditional category",
	"date": "2022-03-08",
	"placement": "Finalist",
	"icon": "emojione-monotone:television",
	"iconColor": "grey",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Ifju-Tudosok-2022.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	]
}

=== skornel02/skornel02/website/src/content/competitions/2022-aszev.json
{
	"$schema": "../../schemas/competition.schema.json",
	"name": "Ágazati és ágazaton belüli specializáció szakmai érettségi vizsgatárgyak versenye - 2022",
	"date": "2022-04-13",
	"placement": "First place",
	"icon": "emojione-monotone:1st-place-medal",
	"highlighted": true,
	"images": [
		{
			"src": "/src/images/competitions/ASZEV2022.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"urls": []
}

=== skornel02/skornel02/website/src/content/achievements/2019-dusza-mobil.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "Dusza Árpád Országos Programozói Emlékverseny - 2019 - Mobile category",
	"date": "2019-12-07",
	"placement": "I. place",
	"icon": "mdi:trophy-award",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Dusza-mobil-2019.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"urls": [
		{
			"name": "Repository",
			"href": "https://github.com/skornel02/FelElek"
		},
		{
			"name": "PlayStore",
			"href": "https://play.google.com/store/apps/details?id=com.hazizz.dusza2019"
		}
	],
	"team": ["erik", "partfo", "sk"]
}

=== skornel02/skornel02/website/src/content/achievements/2025-ws-croatia.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "WorldSkills Croatia 2025 - IT Software Solutions for Business",
	"date": "2025-04-11",
	"placement": "I. place",
	"icon": "mdi:trophy",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/WorldSkills-Croatia-2025-Results.jpg",
			"alt": "Competition results",
			"name": "Results"
		}
	],
	"urls": []
}
