=== skornel02/skornel02/schema/achievements.schema.json
{"$ref":"#/definitions/achievementSchema","definitions":{"achievementSchema":{"type":"object","properties":{"name":{"type":"string"},"date":{"type":"string","format":"date-time"},"placement":{"type":"string"},"icon":{"type":"string"},"iconColor":{"type":"string","default":"orange"},"highlighted":{"type":"boolean","default":false},"images":{"type":"array","items":{"type":"object","properties":{"src":{"type":"string"},"alt":{"type":"string"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:file-image-box"},"buttonClass":{"type":"string","default":"btn btn-sm btn-primary text-white"}},"required":["src","alt","name"],"additionalProperties":false},"default":[]},"pdfs":{"type":"array","items":{"type":"object","properties":{"src":{"type":"string"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:file-pdf"},"buttonClass":{"type":"string","default":"btn btn-sm btn-primary text-white"}},"required":["src","name"],"additionalProperties":false},"default":[]},"urls":{"type":"array","items":{"type":"object","properties":{"href":{"type":"string","format":"uri"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:link-variant"},"buttonClass":{"type":"string","default":"btn btn-sm btn-secondary text-white"}},"required":["href","name"],"additionalProperties":false},"default":[]},"team":{"type":"array","items":{"anyOf":[{"type":"string"},{"type":"object","properties":{"id":{"type":"string"},"collection":{"type":"string"}},"required":["id","collection"],"additionalProperties":false},{"type":"object","properties":{"slug":{"type":"string"},"collection":{"type":"string"}},"required":["slug","collection"],"additionalProperties":false}]}},"blogPost":{"anyOf":[{"type":"string"},{"type":"object","properties":{"id":{"type":"string"},"collection":{"type":"string"}},"required":["id","collection"],"additionalProperties":false},{"type":"object","properties":{"slug":{"type":"string"},"collection":{"type":"string"}},"required":["slug","collection"],"additionalProperties":false}]},"coverImage":{"type":"object","properties":{"src":{"type":"string"},"alt":{"type":"string"},"name":{"type":"string"},"icon":{"type":"string","default":"mdi:file-image-box"},"buttonClass":{"type":"string","default":"btn btn-sm btn-primary text-white"}},"required":["src","alt","name"],"additionalProperties":false}},"required":["name","date","placement","icon"],"additionalProperties":false,"description":"Achievements schema"}},"$schema":"http://json-schema.org/draft-07/schema#"}

=== skornel02/skornel02/website/src/content/achievements/2020-webgraf.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "WebGraf - 2020",
	"date": "2021-01-05",
	"placement": "II. place",
	"icon": "mdi:medal-outline",
	"highlighted": false,
	"team": ["partfo", "sk", "avar"],
	"coverImage": {
		"src": "/src/images/competitions/Webgraf-2020-Cover.jpg",
		"alt": "Podium image",
		"name": "Podium image"
	}
}

=== skornel02/skornel02/website/src/content/achievements/2022-ccna2.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "CCNA Routing and Switching: Routing and Switching Essentials",
	"date": "2022-06-14",
	"placement": "Certificate",
	"icon": "mdi:certificate",
	"highlighted": false,
	"pdfs": [
		{
			"name": "Certificate",
			"src": "/certificates/CCNA-2-certificate.pdf"
		}
	]
}

=== skornel02/skornel02/website/src/content/competitions/2020-accenture.json
{
	"$schema": "https://skornel02.hu/schema/competition.schema.json",
	"name": "Accenture Java competition - 2020",
	"date": "2020-07-06",
	"placement": "Finalist",
	"icon": "mdi:star",
	"highlighted": false,
	"pdfs": [{"name": "Reference", "src": "/assets/competitions/Accenture Java 2020.pdf"}],
	"team": ["fmate", "sk", "vtibor"]
}

=== skornel02/skornel02/website/src/content/competitions/2021-neu.json
{
	"$schema": "https://skornel02.hu/schema/competition.schema.json",
	"name": "Neumann János Egyetem Programming contest - 2020",
	"date": "2021-01-27",
	"placement": "II. place",
	"icon": "emojione-monotone:1st-place-medal",
	"highlighted": false,
	"pdfs": [
		{
			"name": "Competition certificate",
			"src": "/competitions/GAMF programozó verseny 2020.pdf"
		}
	],
	"team": ["partfo", "erik", "sk"]
}

=== skornel02/skornel02/website/src/content/achievements/2025-ws-china-testing.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "WorldSkills China International Exchange Competition 2025 - PO6 Software Testing",
	"date": "2025-06-06",
	"placement": "I. place",
	"icon": "mdi:trophy",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/WorldSkills-China-2025-Results.jpg",
			"alt": "Competition results",
			"name": "Results"
		}
	],
	"urls": [],
	"coverImage": {
		"src": "/src/images/competitions/WorldSkills-China-2025-Competitor.jpg",
		"alt": "Competitor image",
		"name": "Competitor image"
	}
}

=== skornel02/skornel02/website/src/content/achievements/2024-es-preliminary.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "EuroSkills 2025 qualifier - IT Software Solutions for Business",
	"date": "2024-04-26",
	"placement": "I. place",
	"icon": "mdi:trophy-award",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/EuroSkills-Qualifier-2024.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"urls": [
		{
			"name": "Official website",
			"href": "https://worldskillshungary.hu/versenyek/euroskills-herning-2025"
		}
	],
	"coverImage": {
		"src": "/src/images/competitions/EuroSkills-Qualifier-2024-Cover.jpg",
		"alt": "Podium image",
		"name": "Podium image"
	}
}

=== skornel02/skornel02/website/src/content/achievements/2020-nemes.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "Nemes Tihamér Nemzetközi Informatikai Tanulmányi Verseny - 2020 - Programming category",
	"date": "2020-04-15",
	"placement": "39. place",
	"icon": "mdi:star",
	"highlighted": false,
	"pdfs": [{"name": "Reference", "src": "/competitions/Nemes-Tihamer-2020.pdf"}]
}

=== skornel02/skornel02/website/src/content/achievements/2021-merklik.json
{
	"$schema": "https://skornel02.hu/schema/achievements.schema.json",
	"name": "II. Merklik László problémamegoldó verseny",
	"date": "2021-04-15",
	"placement": "Finalist",
	"icon": "mdi:star",
	"highlighted": false,
	"images": [
		{
			"src": "/src/images/competitions/Merklik-2021.jpeg",
			"alt": "Competition certificate",
			"name": "Certificate"
		}
	],
	"team": ["partfo", "sk", "avar"]
}
